#!/usr/bin/env python3
from base import trainer
import sys
import os
import json

# List files in /opt/ml directory
print(os.listdir('/opt/ml'))
# Read and print the contents of /opt/ml/parameters.json
# with open('/opt/ml/parameters.json', 'r') as file:
#     parameters = json.load(file)
#     print(parameters)

if __name__ == "__main__"
    try:
        print("trainer working...")
        trainer()
    except Exception as err:
        print("error loading training scripts...")
        raise err